/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./form/GameUI"
import LoadingProgress from "./form/LoadingProgress"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1000;
    static height:number=800;
    static scaleMode:string="showall";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("form/GameUI.ts",GameUI);
        reg("form/LoadingProgress.ts",LoadingProgress);
    }
}
GameConfig.init();